### ISSUE TITLE
Installing the package

### ISSUE THREAD

**Issue by PavithraKrishnaA** [solarflarecom/ebpf_asm#1]
Hello , I tried to clone the package and install using pip command on ubuntu linux . Unfortunately pip fails stating that it could not find a version that meets the requirements of the package ebpf_asm 
Could you please state what steps to be taken ?

**Comment by ecree-solarflare** [comment]
ebpf_asm isn't on the Python package index, and isn't packaged up to be installed (by pip or otherwise) into site-packages.  (Patches to do this, e.g. with setuptools, would be welcome, but I haven't felt it worth doing myself.)
Instead, just download the source from github, and run ./ebpf_asm.py from the downloaded directory (or put that directory in your $PYTHONPATH, I guess).
